import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'
import { Provider } from 'jotai'
import { Dancing_Script, Oxanium } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
  title: 'Curdapp',
  description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Home', path: '/' },
  { label: 'Account', path: '/account' },
]

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-dancing-script',
})

const oxanium = Oxanium({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-oxanium',
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${dancingScript.variable} ${oxanium.variable} font-oxanium `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AppProviders>
            <AppLayout links={links}>
              <Provider>{children}</Provider>
            </AppLayout>
          </AppProviders>
        </ThemeProvider>
      </body>
    </html>
  )
}
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
